# Traffic Violation Detection Dataset Configuration
path: ./dataset/Traffic Violations  # Dataset root path
train: train/images  # Train images (relative to 'path')
val: valid/images    # Validation images (relative to 'path') 
test: test/images    # Test images (relative to 'path')

# Classes
names: ['10', '11', '12', '13', '13 0 0 0 0', '14', '15', '16', '17', '18', '19', '20', '20 0 0 0 0', '22', '220', '2225', '224', '225', '23', '2323', '23230', '24', '25', '4 0 0 0 0']

# Number of classes
nc: 24
