# Garbage Detection Dataset Configuration
path: ./garbage-detection/data  # Dataset root path
train: train  # Train images (relative to 'path')
val: valid    # Validation images (relative to 'path') 
test: test    # Test images (relative to 'path')

# Classes
names:
  0: cardboard
  1: glass
  2: metal
  3: paper
  4: plastic
  5: trash

# Number of classes
nc: 6