# Helmet Detection Dataset Configuration
path: ./helmet-detection/data  # Dataset root path
train: train  # Train images (relative to 'path')
val: valid    # Validation images (relative to 'path') 
test: test    # Test images (relative to 'path')

# Classes
names:
  0: helmet
  1: no-helmet
  2: person

# Number of classes
nc: 3